begin;

update public.leads
set status = case status
  when 'novo' then 'diagnostico_solicitado'
  when 'diagnostico_enviado' then 'em_analise'
  when 'fechado' then 'negocio_ganho'
  else status
end
where status in ('novo', 'diagnostico_enviado', 'fechado');

alter table public.leads
  alter column status set default 'diagnostico_solicitado';

alter table public.leads
  drop constraint if exists leads_status_check;

alter table public.leads
  add constraint leads_status_check check (
    status in (
      'prospectado',
      'diagnostico_solicitado',
      'em_analise',
      'contato_iniciado',
      'proposta_enviada',
      'negocio_ganho',
      'em_execucao',
      'entregue',
      'sem_retorno',
      'negocio_perdido'
    )
  );

create table if not exists public.lead_historico (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.leads(id) on delete cascade,
  status_anterior text not null,
  novo_status text not null,
  acao text not null,
  motivo_perda text,
  criado_em timestamptz not null default now()
);

create index if not exists lead_historico_lead_id_criado_em_idx
  on public.lead_historico (lead_id, criado_em desc);

alter table public.lead_historico enable row level security;

commit;
